### PR TITLE
Pull command added in Pending changes

### PR DESCRIPTION
**Pull request by AlbertoMonteiro**
Now with this command you can pull remote branch, the command show status when the branch up to date and when pull success. 
When pull rebase fail pop up message dialog with files confliteds.

### CODE REVIEW

**Comment by AlbertoMonteiro** [comment]
Hello?

**Comment by yysun** [comment]
Thanks for the pull request. I have downloaded your code and am reviewing it. It is really good overall. I liked to the part of using sh. One question however. When using http/https protocol, how the password is collected?

**Comment by AlbertoMonteiro** [comment]
I do not worry about it because the SH command do this for me.
Thats the link of the Git Bash
C:\Windows\SysWOW64\cmd.exe /c ""C:\Program Files (x86)\Git\bin\sh.exe" --login -i"

**Comment by yysun** [comment]
This is what happens. When using http/https, msysgit prompts for user name and password. The function RunGitShCmd does not handle this interaction. It hangs at line 112 of GitBash.cs, string output = process.StandardOutput.ReadToEnd();

**Comment by AlbertoMonteiro** [comment]
Yes I know on my first try I used your method and found that authentication problem so I tried to find out how it worked from the command line Git Bash and saw that he used the sh.exe carry it out and pass the two parameters "- login-i ". So I started using it and also discovered that as the CMD parameter to send a command to be executed is the "-c".
It also has a strange thing to git, for example when you push and the push is done successfully the error output has value, which is exactly the message that you did push, see example:
To git@github.com: AlbertoMonteiro / Git-Source-Control-Provider.git
    5fa7159 .. 377c5a6 master -> master

This message is output as an error by even the action is executed successfully.
I added the google talk but I think you have not received the invitation, if you can add me and we can talk
gtalk: betimbrasil@gmail.com
msn: alberto.monteiro@live.com

**Comment by yysun** [comment]
I have added you to gtalk. Or you can email me directly. I can show the steps to re-produce the error.

**Comment by sharwell** [comment]
I'm closing this pull request for the following reasons:
1. It appears the pull/push feature in provided by the Git Extensions "extras" menu.
2. This branch is old and is no longer available in @AlbertoMonteiro repository.
3. The diff is too big to compare against the current implementation.

**Pull request closed without merging**
