### PR TITLE
Multiple items (PendingChanges)

### PR DESCRIPTION
**Pull request by bscheiman**
Fixes issue #18 along with side-effects: 
- Accidental double-clicks on checkbox,
- Nasty cell border.

### CODE REVIEW

**Comment by yysun** [comment]
Thanks Boris.

I pulled down the previous pull request (#19). When trying this pull request (#20). Git reported "patch dose not apply".
When I removed previous pull request, the pull request can apply.

Dose this pull request include changes from previous one?

**Comment by bscheiman** [comment]
Same thing happened to me. Both requests modify the same lines in the
xaml file.

I'll resend the faulty pull request once I fix it. Thanks!

On Jan 25, 2012, at 11:50 AM, Yiyi Sun
reply@reply.github.com
wrote:

**Comment by yysun** [comment]
Thanks a million !

yysun

On Wed, Jan 25, 2012 at 12:53 PM, Boris Scheiman
reply@reply.github.com
wrote:

**Comment by bscheiman** [comment]
Can you accept this pull request?

**Comment by yysun** [comment]
I don't see a new pull request, Pull Request #20 still cannot be applied.

**Comment by bscheiman** [comment]
Thought you said this pull request could be applied w/o #19. If that's the case, I'll close #19 and send a new one... that one is easier to rewrite.

**Comment by yysun** [comment]
#20 can be applied w/o #19, but I already merged #19. Please make the next one can be on top of #19.

**Comment by bscheiman** [comment]
Alright. I'll do it later tonight after work.

**Comment by yysun** [comment]
Thanks again for your help!

**Pull request merged**
